import type { CmsContentBySectionKey } from '@/lib/cms/types';

export const DEFAULT_CMS_CONTENT: CmsContentBySectionKey = {
  siteChrome: {
    brandTitle: 'Kids After School Programs',
    metadataTitle: 'Kids After School Programs',
    metadataDescription:
      'Kids afterschool programs with online registration and a serverless submission API.',
    logoSrc: '/exceed-logo.png',
    logoAlt: 'Exceed Learning Center logo',
    heroImageSrc: '/images/kids/chess-kids.jpg',
    heroImageAlt: 'Kids playing chess at camp',
    accentImageSrc: '/images/kids/blue-leaf.png',
    accentImageAlt: 'Decorative blue leaf',
    navItems: [
      { href: '#about', label: 'About' },
      { href: '#more-information', label: 'More Information' },
      { href: '#afterschool', label: 'Afterschool Programs' },
      { href: '#schedule', label: 'Schedule' },
    ],
    mobileMenuOpenLabel: 'Open menu',
    mobileMenuCloseLabel: 'Close menu',
    scrollToTopLabel: 'Scroll to top',
  },
  about: {
    heading: 'KIDS AFTER SCHOOL PROGRAMS',
    italicLine: 'School is out, but learning continues.',
    paragraph1:
      'Turn after-school hours into an incredible journey. We have designed programs that balance brain-boosting activities with non-stop fun, ensuring your child stays engaged, active, and happy.',
    paragraph2:
      'This is more than just after-school care. It is an opportunity for your child to discover passions, build confidence, and truly ignite their brilliance.',
    buttonLabel: 'Learn More',
    buttonHref: '#more-information',
  },
  moreInformation: {
    headingLine1: 'MORE',
    headingLine2: 'INFORMATION',
    email: 'Afterschool@exceedlearningcenterny.com',
    phone: '+1 (516) 226-3114',
    address: '1360 Willis Ave, Albertson, NY',
    websiteLabel: 'www.exceedlearningcenterny.com',
    websiteHref: 'https://www.exceedlearningcenterny.com',
    imageSrc: '/images/kids/kids-more-information.png',
    imageAlt: 'Children doing arts and crafts at a table',
    videoUrl: '',
  },
  campHighlights: {
    introHeading:
      'In our afterschool program, every day is a new adventure! Your child will enjoy:',
    activities: [
      'CHESS',
      'ABACUS',
      'ART',
      'BRAIN GAMES',
      'HOMEWORK HELP',
    ],
    highlights: [
      {
        boldText: 'Explore New Skills:',
        text: 'Dive into creative projects like arts and crafts, or challenge their minds with brain games and strategic thinking exercises.',
      },
      {
        boldText: 'Make New Friends:',
        text: 'Build friendships and develop teamwork skills in a safe, supportive, and engaging environment.',
      },
      {
        boldText: 'Boost Confidence:',
        text: 'Our hands-on activities and positive encouragement help every child discover their unique talents and feel proud of their accomplishments.',
      },
    ],
    imageSrc: '/images/kids/highlights-kids.png',
    imageAlt: 'Kids working together on activities at camp',
    videoUrl: '',
  },
  programSchedule: {
    badgeLabels: ['CHESS', 'ABACUS', 'ART', 'BRAIN GAMES', 'HOMEWORK HELP'],
    enrollPrefix: 'Enroll your kids now!',
    enrollBold: 'Programs run throughout the year!',
    scheduleTitle: 'Monday to Friday',
    scheduleSubtitle: 'Our programs are available every weekday!',
    scheduleBody:
      "Choose the days that work best for your family's schedule.",
    imageSrc: '/images/kids/child-abacus.png',
    imageAlt: 'Happy child with abacus',
    videoUrl: '',
  },
  afterschoolPrograms: {
    heroTitle: 'Kids Afterschool Programs',
    heroSubtitle: 'Monday to Friday',
    activityOptions: [
      'CHESS',
      'ABACUS',
      'ART',
      'BRAIN GAMES',
      'HOMEWORK HELP',
    ],
    activityScheduleLabel: 'Monday to Friday',
    activityTimeLabel: '4:00 PM - 6:00 PM',
    registrationTitle: 'Registration Form',
    registrationDescription:
      'Fill up the form below to register and we will contact you to settle your payment.',
    parentNameLabel: 'Parent Name',
    parentNamePlaceholder: 'Enter parent name',
    studentNameLabel: 'Student Name',
    studentNamePlaceholder: 'Enter student name',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter email',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'Enter phone number',
    phoneHelperText: 'Use digits, spaces, or + ( )',
    activitiesLabel: 'Select Activities',
    preferredDaysLabel: 'Preferred Days',
    preferredDayOptions: [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
    ],
    selectedCountSuffix: 'selected',
    startDateLabel: 'Desired Start Date',
    startDatePlaceholder: 'Select desired start date',
    notesLabel: 'Notes',
    notesPlaceholder:
      'Share allergies, pickup details, or anything else we should know',
    submitButtonLabel: 'Submit Registration',
    submittingButtonLabel: 'Submitting...',
    requiredFieldsNotice: 'Required fields are marked with *.',
    submissionMessages: {
      invalidFormTitle: 'Please fix the highlighted fields.',
      invalidFormMessage: 'Review the form and try again.',
      successTitle: 'Registration submitted.',
      successMessage: 'Thank you. Your registration was received successfully.',
      errorTitle: 'Submission failed.',
      serverErrorMessage: 'Could not submit the registration right now.',
    },
    validationMessages: {
      invalidPayload: 'Invalid registration payload.',
      genericReview: 'Please review the form and try again.',
      parentNameRequired: 'Parent name is required.',
      parentNameTooLong: 'Parent name must be 120 characters or less.',
      studentNameRequired: 'Student name is required.',
      studentNameTooLong: 'Student name must be 120 characters or less.',
      emailRequired: 'Email is required.',
      emailInvalid: 'Enter a valid email address.',
      phoneRequired: 'Phone number is required.',
      phoneInvalid: 'Enter a valid phone number.',
      activitiesRequired: 'Select at least one activity.',
      preferredDaysRequired: 'Select at least one preferred day.',
      preferredDaysTooLong: 'Preferred days must be 80 characters or less.',
      startDateRequired: 'Desired start date is required.',
      notesTooLong: 'Notes must be 1000 characters or less.',
    },
    pricingTitle: 'Pricing',
    pricingItems: [
      { durationLabel: '1 day/week', price: '$75' },
      { durationLabel: '2 days/week', price: '$150' },
      { durationLabel: '3 days/week', price: '$225' },
      { durationLabel: '4 days/week', price: '$300' },
      { durationLabel: '5 days/week', price: '$375' },
    ],
    discountNotice:
      'Get 40% OFF for 2 or more days of afterschool programs!',
  },
};
